// ============================================================
// Phase D + Phase F regression: clicking a hotspot must produce
// a branch — generated by the entity-interact API, narrated, and
// added to the scene graph. Verifies the per-action cache key
// works (the ?actionType=… plumbing introduced in Phase D) and
// that the manifest-driven readiness dot from Phase F shows up.
// ============================================================

import { test, expect } from '@playwright/test';

test.describe('Hotspot click → branch generation', () => {
  test.setTimeout(120_000);

  test('clicking Rama opens the action menu with readiness dots', async ({ page }) => {
    // Direct deep link — skips the landing CTA so the test focuses on
    // the click-to-branch path.
    await page.goto('/books/ramayana?scene=ayodhya_intro');
    await page.waitForLoadState('domcontentloaded');

    // Hotspot buttons are tagged with `data-testid="hotspot-{target_id}"`
    // by SceneCanvas — that's the stable selector path.
    const ramaHotspot = page.locator('[data-testid="hotspot-rama"]').first();
    await expect(ramaHotspot).toBeVisible({ timeout: 30_000 });

    await ramaHotspot.click();

    // Action menu must open. Verb buttons are tagged with
    // `data-testid="action-{verb}"` for stable selection.
    const talkButton = page.locator('[data-testid="action-talk"]').first();
    await expect(talkButton).toBeVisible({ timeout: 5_000 });

    // The button's data-action-status attribute reflects the manifest's
    // readiness state. We accept 'ready', 'pending', or 'unknown' (the
    // pre-manifest-fetch race) — the regression we're guarding against
    // is "missing the attribute entirely", i.e. the pre-Phase-F state.
    const status = await talkButton.getAttribute('data-action-status');
    expect(status, 'expected action-status attribute on Talk verb').toBeTruthy();
    expect(['ready', 'pending', 'unknown', 'none']).toContain(status);

    // Wait briefly for the manifest fetch to resolve, then re-read.
    // After Phase C+E the status should settle to ready or pending —
    // 'unknown' is only valid as a transient pre-fetch state.
    await page.waitForTimeout(2_000);
    const settledStatus = await talkButton.getAttribute('data-action-status');
    expect(['ready', 'pending']).toContain(settledStatus);
  });

  test('selecting Talk produces narration content', async ({ page }) => {
    await page.goto('/books/ramayana?scene=ayodhya_intro');
    await page.waitForLoadState('domcontentloaded');

    const ramaHotspot = page.locator('[data-testid="hotspot-rama"]').first();
    await expect(ramaHotspot).toBeVisible({ timeout: 30_000 });
    await ramaHotspot.click();

    const talkButton = page.locator('[data-testid="action-talk"]').first();
    await expect(talkButton).toBeVisible({ timeout: 5_000 });

    // Track the entity-interact response so the test fails fast on
    // a 4xx/5xx instead of waiting for narration that will never come.
    const interactResponse = page.waitForResponse(
      r => r.url().includes('/api/livebook/entity-interact'),
      { timeout: 60_000 },
    ).catch(() => null);

    await talkButton.click();
    const response = await interactResponse;

    // Either the API call landed (preferred — fastest), or the cache
    // hit fast enough that no fetch was needed and the warmed branch
    // came from the in-memory scene graph. Both are valid outcomes.
    if (response) {
      expect(response.ok(), 'entity-interact must return 2xx').toBeTruthy();
    }

    // The branch should advance the visible narration. Since narration
    // text is AI-generated we don't pin the wording, but the page
    // should still contain Rama's name somewhere visibly.
    const narrationCandidate = page.getByText(/rama/i).first();
    await expect(narrationCandidate).toBeVisible({ timeout: 30_000 });
  });
});
